### ISSUE TITLE
HTTP status page not handling errors correctly when querying remote status

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#164]
wget http://localhost:443/v1/status

results in the following log to be written:
`2019-01-16 23:32:25,746 irrd[6074]: [twisted#CRITICAL]
Traceback (most recent call last):
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/web/server.py", line 199, in process
    self.render(resrc)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/web/server.py", line 259, in render
    body = resrc.render(self)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd/server/http/http_resources.py", line 22, in render_GET
    result_txt = DatabaseStatusRequest().generate_status()
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd/server/http/request_handlers.py", line 31, in generate_status
    results = [self._generate_header(), self._generate_statistics_table(), self._generate_source_detail()]
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd/server/http/request_handlers.py", line 105, in _generate_source_detail
    remote_information = self._generate_remote_status_info(nrtm_host, nrtm_port, source)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd/server/http/request_handlers.py", line 137, in _generate_remote_status_info
    source_status = whois_query_source_status(nrtm_host, nrtm_port, source)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd/utils/whois_client.py", line 116, in whois_query_source_status
    remote_status = whois_query_irrd(host, port, f'!j{source}')
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd/utils/whois_client.py", line 71, in whois_query_irrd
    data = s.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
2019-01-16 23:32:25,748 irrd[6074]: [twisted#INFO] "::1" - - [16/Jan/2019:23:32:23 +0000] "GET /v1/status HTTP/1.1" 500 95 "-" "Wget/1.18 (linux-gnu)"
2019-01-16 23:32:25,749 irrd[6074]: [twisted#WARNING] /home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/web/server.py:201: builtins.ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('128.241.192.40', 36822)>`

Also there does not seem be any documentations on the web server.

btw, / and /v1 return a 404 not found error.

This was found in irrd-4.0.0rc1

**Comment by mxsasha** [comment]
Split the issue about missing documentation into #170.

It looks like this error is caused by a connection reset while attempting to query the remote status information from an NRTM source. That error needs graceful handling.
