### ISSUE TITLE
unnecessary tracebacks

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#177]
seen in 4.0.0-rc5
2019-01-25 00:17:14,666 irrd[30726]: [irrd.mirroring.mirror_runners_import#CRITICAL] An exception occurred while attempting a mirror update or initial import for APNIC: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd/mirroring/mirror_runners_import.py", line 44, in run
    self.update_stream_runner.run(serial_newest_seen, database_handler=self.database_handler)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd/mirroring/mirror_runners_import.py", line 207, in run
    response = whois_query(nrtm_host, nrtm_port, query, end_markings)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd/utils/whois_client.py", line 36, in whois_query
    data = s.recv(1024*1024)
ConnectionResetError: [Errno 104] Connection reset by peer

the first part is all that is needed there:
2019-01-25 00:17:14,666 irrd[30726]: [irrd.mirroring.mirror_runners_import#CRITICAL] An exception occurred while attempting a mirror update or initial import for APNIC: [Errno 104] Connection reset by peer

**Comment by troy2914** [comment]
Also the level of CRITICAL seems higher then needed.  ALERT seems better.

**Comment by mxsasha** [comment]
Yes, CRITICAL is too high. This is a catch for any unexpected exceptions in the mirroring process. I will add some more specific catches with errors we expect, that log less info, which will reduce the number of tracebacks.

We don't have ALERT - I think ERROR would be the most appropriate level. WARNING seems weak. CRITICAL should be reserved to "a data inconsistency may have occurred that may not fix itself".
