### ISSUE TITLE
invalid v4 route prefixes are being accept

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#190]
4.0.0rc4

saw this from irrd2

    route:      04.2.248.0/24
    descr:      Akamai MIA
    origin:     AS20940
    mnt-by:     MAINT-NTTCOM-RA
    changed:    kpack@us.ntt.net 20181219
    source:     NTTCOM

irrd4 converted that to:

    route:          4.2.248.0/24
    descr:          Akamai MIA
    origin:         AS20940
    mnt-by:         MAINT-NTTCOM-RA
    changed:        kpack@us.ntt.net 20181219
    source:         NTTCOM

irrd4 should have rejected that route due to the leading 0 in a v4 address.

fyi,  those were suppose to be 204.2.248.0/24

**Comment by job** [comment]
@troy2914 do you want to reject submissions for just the authoritative databases, or also for what we receive over NRTM / dumps?

**Comment by troy2914** [comment]
All, garbage is garbage no matter where it came from.

**Comment by mxsasha** [comment]
We can work on this on the support contract, if you want. Not a lot of work probably, but a few questions first:

1. IPv4 prefixes that start with a 0 should be rejected, right?
2. How about 192.0.02.0/24?
3. How about IPv6 addresses that start with a 0?
4. Should this also affect route set members?
5. How about AS numbers, e.g. AS0123?

**Comment by job** [comment]
Ideally we can point at some RFCs about canonical notation of ipv6 and ipv4
prefixes.

**Comment by mxsasha** [comment]
What are we going to do with this?

**Comment by job** [comment]
Perhaps this canonicalisation test is sufficient:

```>>> "02.24.24.0/24" == str(ipaddress.IPv4Network("02.24.24.0/24"))
False
>>> "02.24.24.0/24" == str(ipaddress.IPv4Network("02.24.024.0/24"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ipaddress.py", line 1523, in __init__
    self.network_address = IPv4Address(addr)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ipaddress.py", line 1327, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ipaddress.py", line 1166, in _ip_int_from_string
    raise AddressValueError("%s in %r" % (exc, ip_str)) from None
ipaddress.AddressValueError: Ambiguous (octal/decimal) value in '024' not permitted in '02.24.024.0'```

**Comment by job** [comment]
Do we still have examples like these?

**Comment by sumkincpp** [comment]
Another example: 07.35.33.0/27 in BELL-RC in RADB
https://www.radb.net/query?advanced_query=1&keywords=07.35.33.0%2F27&-T+option=&ip_option=&-i+option=

Python 3.6 has no Problems incorrectly converting it to 7.35.33.0/27, though it should be 207.35.33.0/27.
Python 3.8.10 raises Exception for `ipaddress.ip_network(address=prefix)`, and Python 3.6 not.
```
  File "/usr/lib/python3.8/ipaddress.py", line 83, in ip_network
    raise ValueError('%r does not appear to be an IPv4 or IPv6 network' %
ValueError: '07.35.33.0/27' does not appear to be an IPv4 or IPv6 network
```
