### ISSUE TITLE
builtins.ImportError: cannot import name 'config_init'

### ISSUE THREAD

**Issue by Rom4nksl** [irrdnet/irrd4#215]
Hello!
I have a problem, installed by manual https://irrd4.readthedocs.io/en/latest/admins/deployment.html#installing-irrd
and gives an error message:
`/home/irrd/irrd-venv/bin/twistd --uid=irrd --pidfile=/var/irrd.pid irrd`

```
[admin@whois ~]$ /home/irrd/irrd-venv/bin/twistd --uid=irrd --pidfile=/var/irrd.pid irrd
Unhandled Error
Traceback (most recent call last):
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/application/app.py", line 636, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/usage.py", line 262, in parseOptions
    for (cmd, short, parser, doc) in self.subCommands:
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/application/app.py", line 653, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/plugin.py", line 213, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/plugin.py", line 171, in getCache
    provider = pluginModule.load()
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd-4.0.0rc8-py3.6.egg/twisted/plugins/irrd_plugin.py", line 15, in <module>
    from irrd.conf import config_init, get_setting, CONFIG_PATH_DEFAULT
builtins.ImportError: cannot import name 'config_init'

Unhandled Error
Traceback (most recent call last):
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/usage.py", line 447, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/usage.py", line 484, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/application/app.py", line 653, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/plugin.py", line 213, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/plugin.py", line 171, in getCache
    provider = pluginModule.load()
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd-4.0.0rc8-py3.6.egg/twisted/plugins/irrd_plugin.py", line 15, in <module>
    from irrd.conf import config_init, get_setting, CONFIG_PATH_DEFAULT
builtins.ImportError: cannot import name 'config_init'

Usage: twistd [options]
Options:
....................
/home/irrd/irrd-venv/bin/twistd: Unknown command: irrd
[admin@whois ~]$ 
```
File "/home/irrd/irrd-venv/lib/python3.6/site-packages/irrd-4.0.0rc8-py3.6.egg/twisted/plugins/irrd_plugin.py", line 15, in <module>
    from irrd.conf import config_init, get_setting, CONFIG_PATH_DEFAULT
builtins.ImportError: cannot import name 'config_init'

```
[admin@whois ~]$ uname -a
Linux whois.test 2.6.32-754.12.1.el6.x86_64 #1 SMP Tue Apr 9 14:52:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[admin@whois ~]$ python3 -V
Python 3.6.8

and PostgreSQL-9.6
```

```
[admin@whois ~]$ /home/irrd/irrd-venv/bin/twistd -b --uid=irrd --pidfile=/var/irrd.pid irrd       
Jumping into debugger for post-mortem of exception 'cannot import name 'config_init'':
> /home/irrd/irrd-venv/lib/python3.6/site-packages/irrd-4.0.0rc8-py3.6.egg/twisted/plugins/irrd_plugin.py(15)<module>()
-> from irrd.conf import config_init, get_setting, CONFIG_PATH_DEFAULT
(Pdb) quit
```

any ideas? what is the problem?

**Comment by Rom4nksl** [comment]
```
[admin@whois ~]$ cat /etc/*release*
CentOS release 6.10 (Final)
CentOS release 6.10 (Final)
CentOS release 6.10 (Final)
cpe:/o:centos:linux:6:GA
```

**Comment by job** [comment]
Please use python 3.7

**Comment by Rom4nksl** [comment]
ok. i'm install python3.7:

```
(irrd-venv) root@whois:/home/irrd/irrd-venv/bin# python3 -V
Python 3.6.8
(irrd-venv) root@whois:/home/irrd/irrd-venv/bin# deactivate 
root@whois:/home/irrd/irrd-venv/bin# ln -fs /usr/bin/python3.
python3.5          python3.5-config   python3.5m         python3.5m-config  python3.6          python3.6-config   python3.6m         python3.6m-config  python3.7          python3.7-config   python3.7m         python3.7m-config
root@whois:/home/irrd/irrd-venv/bin# ln -fs /usr/bin/python3.7 /usr/bin/python3
root@whois:/home/irrd/irrd-venv/bin# virtualenv -p python3 /home/irrd/irrd-venv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/irrd/irrd-venv/bin/python3
Not overwriting existing python script /home/irrd/irrd-venv/bin/python (you must use /home/irrd/irrd-venv/bin/python3)
Installing setuptools, pkg_resources, pip, wheel...done.
root@whois:/home/irrd/irrd-venv/bin# source /home/irrd/irrd-venv/bin/activate
(irrd-venv) root@whois:/home/irrd/irrd-venv/bin# python3 -V
Python 3.7.3
```

and install irrd again... 
```
(irrd-venv) root@whois:/home/irrd/irrd-venv/bin# twistd --uid=irrd --pidfile=/var/irrd.pid irrd
Usage: twistd [options]
Options:
  -b, --debug          Run the application in the Python Debugger (implies
                       nodaemon),         sending SIGUSR2 will drop into
                       debugger
      --chroot=        Chroot to a supplied directory before running
  -d, --rundir=        Change to a supplied directory before running [default:
                       .]
  -e, --encrypted      The specified tap/aos file is encrypted.
      --euid           Set only effective user-id rather than real user-id.
                       (This option has no effect unless the server is running
                       as root, in which case it means not to shed all
                       privileges after binding ports, retaining the option to
                       regain privileges in cases such as spawning processes.
                       Use with caution.)
  -f, --file=          read the given .tap file [default: twistd.tap]
  -g, --gid=           The gid to run as.  If not specified, the default gid
                       associated with the specified --uid is used.
      --help           Display this help and exit.
      --help-reactors  Display a list of possibly available reactor names.
  -l, --logfile=       log to a specified file, - for stdout
      --logger=        A fully-qualified name to a log observer factory to use
                       for the initial log observer.  Takes precedence over
                       --logfile and --syslog (when available).
  -n, --nodaemon       don't daemonize, don't use default umask of 0077
  -o, --no_save        do not save state on shutdown
      --originalname   Don't try to change the process name
  -p, --profile=       Run in profile mode, dumping results to specified file.
      --pidfile=       Name of the pidfile [default: twistd.pid]
      --prefix=        use the given prefix when syslogging [default: twisted]
      --profiler=      Name of the profiler to use (profile, cprofile).
                       [default: cprofile]
  -r, --reactor=       Which reactor to use (see --help-reactors for a list of
                       possibilities)
  -s, --source=        Read an application from a .tas file (AOT format).
      --savestats      save the Stats object rather than the text output of the
                       profiler.
      --spew           Print an insanely verbose log of everything that happens.
                       Useful when debugging freezes or locks in complex code.
      --syslog         Log to syslog, not to file
  -u, --uid=           The uid to run as.
      --umask=         The (octal) file creation mask to apply.
      --version        Print version information and exit.
  -y, --python=        read an application from within a Python file (implies
                       -o)

twistd reads a twisted.application.service.Application out of a file and runs
it.
Commands:
    conch            A Conch SSH service.
    dns              A domain name server.
    ftp              An FTP server.
    inetd            An inetd(8) replacement.
    manhole          An interactive remote debugger service accessible via
                     telnet and ssh and providing syntax coloring and basic line
                     editing functionality.
    portforward      A simple port-forwarder.
    procmon          A process watchdog / supervisor
    socks            A SOCKSv4 proxy service.
    web              A general-purpose web server which can serve from a
                     filesystem or application resource.
    words            A modern words server
    xmpp-router      An XMPP Router server

/home/irrd/irrd-venv/bin/twistd: Unknown command: irrd
(irrd-venv) root@whois:/home/irrd/irrd-venv/bin# 
```
/home/irrd/irrd-venv/bin/twistd: Unknown command: irrd

what am I doing wrong? ((

**Comment by job** [comment]
What was the issue? can you share?
